# --- Major Trading Ports Data (Manually Populated with Lat/Long) ---
# These are approximate coordinates for major cities associated with the ports.
# For high-accuracy, you'd use dedicated GIS data or more precise geocoding.
MAJOR_TRADING_PORTS_DATA = [
    # Global & Major Chinese Ports
    {"port_name": "Port of Shanghai", "city": "Shanghai", "country": "China", "category": "global_port", "lat": 31.2304, "lon": 121.4737},
    {"port_name": "Port of Singapore", "city": "Singapore", "country": "Singapore", "category": "global_port", "lat": 1.3521, "lon": 103.8198},
    {"port_name": "Port of Ningbo-Zhoushan", "city": "Ningbo", "country": "China", "category": "global_port", "lat": 29.8683, "lon": 121.5439},
    {"port_name": "Port of Shenzhen", "city": "Shenzhen", "country": "China", "category": "global_port", "lat": 22.5428, "lon": 114.0579},
    {"port_name": "Qingdao Port", "city": "Qingdao", "country": "China", "category": "global_port", "lat": 36.0673, "lon": 120.3826},
    {"port_name": "Port of Guangzhou", "city": "Guangzhou", "country": "China", "category": "global_port", "lat": 23.1291, "lon": 113.2644},
    {"port_name": "Port of Tianjin", "city": "Tianjin", "country": "China", "category": "global_port", "lat": 39.0842, "lon": 117.2009},
    {"port_name": "Port of Xiamen", "city": "Xiamen", "country": "China", "category": "global_port", "lat": 24.4798, "lon": 118.0894},
    {"port_name": "Port of Dalian", "city": "Dalian", "country": "China", "category": "global_port", "lat": 38.9155, "lon": 121.6147},
    {"port_name": "Port of Rizhao", "city": "Rizhao", "country": "China", "category": "global_port", "lat": 35.4267, "lon": 119.4623},
    {"port_name": "Taicang Port (Runhe Terminal)", "city": "Suzhou", "country": "China", "category": "global_port", "lat": 35.4267, "lon": 119.4623},
    {"port_name": "Port of Yingkou", "city": "Yingkou", "country": "China", "category": "global_port", "lat": 40.6698, "lon": 122.2359},
    {"port_name": "Port of Los Angeles", "city": "Los Angeles", "country": "USA", "category": "global_port", "lat": 34.0522, "lon": -118.2437},
    {"port_name": "Port of Long Beach", "city": "Long Beach", "country": "USA", "category": "global_port", "lat": 33.7701, "lon": -118.1937},
    {"port_name": "Port of Hong Kong", "city": "Hong Kong", "country": "China", "category": "global_port", "lat": 22.3027, "lon": 114.1747},
    {"port_name": "Port of Rotterdam", "city": "Rotterdam", "country": "Netherlands", "category": "global_port", "lat": 51.9225, "lon": 4.47917},
    {"port_name": "Port of Antwerp-Bruges", "city": "Antwerp", "country": "Belgium", "category": "global_port", "lat": 51.2210, "lon": 4.3997},
    {"port_name": "Port Klang", "city": "Port Klang", "country": "Malaysia", "category": "global_port", "lat": 3.0034, "lon": 101.3831},
    {"port_name": "Port of Tanjung Pelepas", "city": "Tanjung Pelepas", "country": "Malaysia", "category": "global_port", "lat": 1.3667, "lon": 103.5333},
    {"port_name": "Port of New York and New Jersey", "city": "New York", "country": "USA", "category": "global_port", "lat": 40.7128, "lon": -74.0060},
    {"port_name": "Laem Chabang Port", "city": "Laem Chabang", "country": "Thailand", "category": "global_port", "lat": 13.1098, "lon": 100.9157},
    {"port_name": "Port of Hamburg", "city": "Hamburg", "country": "Germany", "category": "global_port", "lat": 53.5511, "lon": 9.9937},
    {"port_name": "Port of Colombo", "city": "Colombo", "country": "Sri Lanka", "category": "global_port", "lat": 6.9271, "lon": 79.8612},
    {"port_name": "Port of Busan", "city": "Busan", "country": "South Korea", "category": "global_port", "lat": 35.1796, "lon": 129.0756},
    {"port_name": "Port of Tokyo", "city": "Tokyo", "country": "Japan", "category": "global_port", "lat": 35.6895, "lon": 139.6917},
    {"port_name": "Port of Osaka", "city": "Osaka", "country": "Japan", "category": "global_port", "lat": 34.6937, "lon": 135.5022},
    {"port_name": "Port of Manila", "city": "Manila", "country": "Philippines", "category": "global_port", "lat": 14.5995, "lon": 120.9842},
    {"port_name": "Port of Ho Chi Minh City", "city": "Ho Chi Minh City", "country": "Vietnam", "category": "global_port", "lat": 10.8231, "lon": 106.6297},
    {"port_name": "Port of Jakarta", "city": "Jakarta", "country": "Indonesia", "category": "global_port", "lat": -6.2088, "lon": 106.8456},
    {"port_name": "Port of Bangkok", "city": "Bangkok", "country": "Thailand", "category": "global_port", "lat": 13.7563, "lon": 100.5018},
    {"port_name": "Port of Surabaya", "city": "Surabaya", "country": "Indonesia", "category": "global_port", "lat": -7.2575, "lon": 112.7521},
    {"port_name": "Port of Cat Lai (Ho Chi Minh City)", "city": "Ho Chi Minh City", "country": "Vietnam", "category": "global_port", "lat": 10.8231, "lon": 106.6297},
    {"port_name": "Port of Sihanoukville", "city": "Sihanoukville", "country": "Cambodia", "category": "global_port", "lat": 10.6277, "lon": 103.5225},
    {"port_name": "Port of Haiphong", "city": "Haiphong", "country": "Vietnam", "category": "global_port", "lat": 20.8449, "lon": 106.6881},

    # Major US Ports (Expanded)
    {"port_name": "Port of Los Angeles", "city": "Los Angeles", "country": "USA", "category": "global_port", "lat": 34.0522, "lon": -118.2437},
    {"port_name": "Port of Long Beach", "city": "Long Beach", "country": "USA", "category": "global_port", "lat": 33.7701, "lon": -118.1937},
    {"port_name": "Port of New York and New Jersey", "city": "New York", "country": "USA", "category": "global_port", "lat": 40.7128, "lon": -74.0060},
    {"port_name": "Port of Savannah", "city": "Savannah", "country": "USA", "category": "us_port", "lat": 32.0761, "lon": -81.0883},
    {"port_name": "Port of Houston", "city": "Houston", "country": "USA", "category": "us_port", "lat": 29.7604, "lon": -95.3698},
    {"port_name": "Northwest Seaport Alliance (Seattle & Tacoma)", "city": "Seattle", "country": "USA", "category": "us_port", "lat": 47.6062, "lon": -122.3321},
    {"port_name": "Northwest Seaport Alliance (Seattle & Tacoma)", "city": "Tacoma", "country": "USA", "category": "us_port", "lat": 47.2529, "lon": -122.4443},
    {"port_name": "Port of Virginia (Norfolk)", "city": "Norfolk", "country": "USA", "category": "us_port", "lat": 36.8508, "lon": -76.2859},
    {"port_name": "Port of Oakland", "city": "Oakland", "country": "USA", "category": "us_port", "lat": 37.8044, "lon": -122.2712},
    {"port_name": "Port of Charleston", "city": "Charleston", "country": "USA", "category": "us_port", "lat": 32.7765, "lon": -79.9311},
    {"port_name": "Port of Miami", "city": "Miami", "country": "USA", "category": "us_port", "lat": 25.7617, "lon": -80.1918},


    # Indian Ports
    {"port_name": "Jawaharlal Nehru Port (JNPT) or Nhava Sheva", "city": "Navi Mumbai", "state": "Maharashtra", "country": "India", "category": "indian_port", "lat": 19.0330, "lon": 73.0297},
    {"port_name": "Mumbai Port", "city": "Mumbai", "state": "Maharashtra", "country": "India", "category": "indian_port", "lat": 19.0760, "lon": 72.8777},
    {"port_name": "Mundra Port", "city": "Mundra", "state": "Gujarat", "country": "India", "category": "indian_port", "lat": 22.8687, "lon": 69.7214},
    {"port_name": "Mundra Port", "city": "Surat", "state": "Gujarat", "country": "India", "category": "indian_port", "lat": 22.8687, "lon": 69.7214},
    {"port_name": "Kandla Port (Deendayal Port)", "city": "Kandla", "state": "Gujarat", "country": "India", "category": "indian_port", "lat": 23.0487, "lon": 70.2281},
    {"port_name": "Chennai Port", "city": "Chennai", "state": "Tamil Nadu", "country": "India", "category": "indian_port", "lat": 13.0827, "lon": 80.2707},
    {"port_name": "Visakhapatnam Port", "city": "Visakhapatnam", "state": "Andhra Pradesh", "country": "India", "category": "indian_port", "lat": 17.6868, "lon": 83.2185},
    {"port_name": "Paradip Port", "city": "Paradip", "state": "Odisha", "country": "India", "category": "indian_port", "lat": 20.2520, "lon": 86.6669},
    {"port_name": "Haldia Dock Complex", "city": "Haldia", "state": "West Bengal", "country": "India", "category": "indian_port", "lat": 22.0725, "lon": 88.0827},
    {"port_name": "Kolkata Port (Shyama Prasad Mookerjee Port Trust)", "city": "Kolkata", "state": "West Bengal", "country": "India", "category": "indian_port", "lat": 22.5726, "lon": 88.3639},
    {"port_name": "Cochin Port", "city": "Kochi", "state": "Kerala", "country": "India", "category": "indian_port", "lat": 9.9312, "lon": 76.2673},
    {"port_name": "New Mangalore Port", "city": "Mangaluru", "state": "Karnataka", "country": "India", "category": "indian_port", "lat": 12.9142, "lon": 74.8560},
    {"port_name": "Mormugao Port", "city": "Mormugao", "state": "Goa", "country": "India", "category": "indian_port", "lat": 15.2533, "lon": 73.8078},
    {"port_name": "V.O. Chidambaranar Port (Tuticorin Port)", "city": "Thoothukudi", "state": "Tamil Nadu", "country": "India", "category": "indian_port", "lat": 8.7642, "lon": 78.1348},
    {"port_name": "Kamarajar Port (Ennore Port)", "city": "Ennore", "state": "Tamil Nadu", "country": "India", "category": "indian_port", "lat": 13.2625, "lon": 80.3429},
    {"port_name": "Kamarajar Port (Ennore Port)", "city": "Chennai", "state": "Tamil Nadu", "country": "India", "category": "indian_port", "lat": 13.2625, "lon": 80.3429},

    # Middle East Ports
    {"port_name": "Port of Jebel Ali", "city": "Dubai", "country": "UAE", "category": "middle_east_port", "lat": 25.0742, "lon": 55.1868},
    {"port_name": "Khalifa Port", "city": "Abu Dhabi", "country": "UAE", "category": "middle_east_port", "lat": 24.4539, "lon": 54.3773},
    {"port_name": "Sohar Port", "city": "Sohar", "country": "Oman", "category": "middle_east_port", "lat": 24.3333, "lon": 56.7333},
    {"port_name": "Jeddah Islamic Port", "city": "Jeddah", "country": "Saudi Arabia", "category": "middle_east_port", "lat": 21.4858, "lon": 39.1925},
    {"port_name": "King Abdullah Port", "city": "King Abdullah Economic City", "country": "Saudi Arabia", "category": "middle_east_port", "lat": 22.3667, "lon": 39.0667},
    {"port_name": "King Abdulaziz Port", "city": "Dammam", "country": "Saudi Arabia", "category": "middle_east_port", "lat": 26.4210, "lon": 50.0900},
    {"port_name": "Hamad Port", "city": "Al Wakrah", "country": "Qatar", "category": "middle_east_port", "lat": 25.1667, "lon": 51.6000},
    {"port_name": "Port Salalah", "city": "Salalah", "country": "Oman", "category": "middle_east_port", "lat": 17.0151, "lon": 54.0924},
    {"port_name": "Jubail Commercial Port", "city": "Jubail", "country": "Saudi Arabia", "category": "middle_east_port", "lat": 27.0135, "lon": 49.6631},
    {"port_name": "Port of Fujairah", "city": "Fujairah", "country": "UAE", "category": "middle_east_port", "lat": 25.1167, "lon": 56.3400},

    # Africa Ports
    {"port_name": "Port of Durban", "city": "Durban", "country": "South Africa", "category": "africa_port", "lat": -29.8587, "lon": 31.0218},
    {"port_name": "Port of Richards Bay", "city": "Richards Bay", "country": "South Africa", "category": "africa_port", "lat": -28.7667, "lon": 32.0333},
    {"port_name": "Port of Cape Town", "city": "Cape Town", "country": "South Africa", "category": "africa_port", "lat": -33.9249, "lon": 18.4241},
    {"port_name": "Port of Lagos (Apapa & Tin Can Island)", "city": "Lagos", "country": "Nigeria", "category": "africa_port", "lat": 6.5244, "lon": 3.3792},
    {"port_name": "Tincan Island Port", "city": "Lagos", "country": "Nigeria", "category": "africa_port", "lat": 6.5244, "lon": 3.3792},
    {"port_name": "Port of Mombasa", "city": "Mombasa", "country": "Kenya", "category": "africa_port", "lat": -4.0435, "lon": 39.6682},
    {"port_name": "Port of Tanger-Med", "city": "Tanger-Med", "country": "Morocco", "category": "africa_port", "lat": 35.8828, "lon": -5.5039},
    {"port_name": "Port of Dar es Salaam", "city": "Dar es Salaam", "country": "Tanzania", "category": "africa_port", "lat": -6.7924, "lon": 39.2083},
    {"port_name": "Port of Djibouti", "city": "Djibouti City", "country": "Djibouti", "category": "africa_port", "lat": 11.8251, "lon": 42.5903},
    {"port_name": "Port of Abidjan", "city": "Abidjan", "country": "Ivory Coast", "category": "africa_port", "lat": 5.3167, "lon": -4.0300},
    {"port_name": "Port of Tema", "city": "Tema", "country": "Ghana", "category": "africa_port", "lat": 5.6797, "lon": 0.0163},
    {"port_name": "Port of Beira", "city": "Beira", "country": "Mozambique", "category": "africa_port", "lat": -19.8436, "lon": 34.8692},
    {"port_name": "Port of Walvis Bay", "city": "Walvis Bay", "country": "Namibia", "category": "africa_port", "lat": -22.9575, "lon": 14.5053},
    {"port_name": "Port of Casablanca", "city": "Casablanca", "country": "Morocco", "category": "africa_port", "lat": 33.5731, "lon": -7.5898},
    {"port_name": "Port of Algiers", "city": "Algiers", "country": "Algeria", "category": "africa_port", "lat": 36.7538, "lon": 3.0583},
    {"port_name": "Port of Douala", "city": "Douala", "country": "Cameroon", "category": "africa_port", "lat": 4.0511, "lon": 9.7679},

    # Latin American Ports (including Mexico and Caribbean)
    # Brazil
    {"port_name": "Port of Santos", "city": "Santos", "country": "Brazil", "category": "latin_america_port", "lat": -23.9608, "lon": -46.3333},
    {"port_name": "Port of Itajaí", "city": "Itajaí", "country": "Brazil", "category": "latin_america_port", "lat": -26.9063, "lon": -48.6625},
    {"port_name": "Port of Paranaguá", "city": "Paranaguá", "country": "Brazil", "category": "latin_america_port", "lat": -25.5152, "lon": -48.5147},
    {"port_name": "Port of Rio Grande", "city": "Rio Grande", "country": "Brazil", "category": "latin_america_port", "lat": -32.0353, "lon": -52.0986},
    {"port_name": "Port of Navegantes", "city": "Navegantes", "country": "Brazil", "category": "latin_america_port", "lat": -26.8996, "lon": -48.6534},
    {"port_name": "Port of Rio de Janeiro", "city": "Rio de Janeiro", "country": "Brazil", "category": "latin_america_port", "lat": -22.9068, "lon": -43.1729},
    {"port_name": "Port of Salvador", "city": "Salvador", "country": "Brazil", "category": "latin_america_port", "lat": -12.9714, "lon": -38.5014},
    # Guyana
    {"port_name": "Port of Georgetown", "city": "Georgetown", "country": "Guyana", "category": "latin_america_port", "lat": 6.8013, "lon": -58.1550},
    # Suriname
    {"port_name": "Port of Paramaribo", "city": "Paramaribo", "country": "Suriname", "category": "latin_america_port", "lat": 5.8520, "lon": -55.2038},
    # Mexico
    {"port_name": "Port of Manzanillo", "city": "Manzanillo", "country": "Mexico", "category": "latin_america_port", "lat": 19.0520, "lon": -104.3160},
    {"port_name": "Port of Veracruz", "city": "Veracruz", "country": "Mexico", "category": "latin_america_port", "lat": 19.1809, "lon": -96.1429},
    {"port_name": "Port of Lázaro Cárdenas", "city": "Lázaro Cárdenas", "country": "Mexico", "category": "latin_america_port", "lat": 17.9500, "lon": -102.2000},
    {"port_name": "Port of Altamira", "city": "Altamira", "country": "Mexico", "category": "latin_america_port", "lat": 22.4167, "lon": -97.9333},
    {"port_name": "Port of Ensenada", "city": "Ensenada", "country": "Mexico", "category": "latin_america_port", "lat": 31.8660, "lon": -116.6080},
    # Caribbean Ports
    {"port_name": "Port of Kingston", "city": "Kingston", "country": "Jamaica", "category": "latin_america_port", "lat": 17.9700, "lon": -76.7900},
    {"port_name": "Caucedo Port", "city": "Caucedo", "country": "Dominican Republic", "category": "latin_america_port", "lat": 18.4200, "lon": -69.6600}, # Near Santo Domingo
    {"port_name": "Freeport Container Port", "city": "Freeport", "country": "Bahamas", "category": "latin_america_port", "lat": 26.5494, "lon": -78.7078},
    {"port_name": "Port of Port of Spain", "city": "Port of Spain", "country": "Trinidad and Tobago", "category": "latin_america_port", "lat": 10.6667, "lon": -61.5167},
    {"port_name": "Port of Cristobal", "city": "Colon", "country": "Panama", "category": "latin_america_port", "lat": 9.3590, "lon": -79.9048},
    {"port_name": "Port of Balboa", "city": "Panama City", "country": "Panama", "category": "latin_america_port", "lat": 8.9824, "lon": -79.5199},
    {"port_name": "Port of Mariel", "city": "Mariel", "country": "Cuba", "category": "latin_america_port", "lat": 22.9906, "lon": -82.7533},
    {"port_name": "Port of San Juan", "city": "San Juan", "country": "Puerto Rico", "category": "latin_america_port", "lat": 18.4655, "lon": -66.1057},
    {"port_name": "Port of Willemstad", "city": "Willemstad", "country": "Curaçao", "category": "latin_america_port", "lat": 12.1000, "lon": -68.9333},
    {"port_name": "Port of Bridgetown", "city": "Bridgetown", "country": "Barbados", "category": "latin_america_port", "lat": 13.1073, "lon": -59.6200},

    # Mediterranean Ports
    {"port_name": "Port of Piraeus", "city": "Piraeus", "country": "Greece", "category": "mediterranean_port", "lat": 37.9429, "lon": 23.6472},
    {"port_name": "Port of Valencia", "city": "Valencia", "country": "Spain", "category": "mediterranean_port", "lat": 39.4699, "lon": -0.3763},
    {"port_name": "Port of Algeciras", "city": "Algeciras", "country": "Spain", "category": "mediterranean_port", "lat": 36.1366, "lon": -5.4600},
    {"port_name": "Port of Barcelona", "city": "Barcelona", "country": "Spain", "category": "mediterranean_port", "lat": 41.3851, "lon": 2.1734},
    {"port_name": "Port of Genoa", "city": "Genoa", "country": "Italy", "category": "mediterranean_port", "lat": 44.4056, "lon": 8.9463},
    {"port_name": "Port of Marsaxlokk (Malta Freeport)", "city": "Marsaxlokk", "country": "Malta", "category": "mediterranean_port", "lat": 35.8422, "lon": 14.5407},
    {"port_name": "Port of Izmir", "city": "Izmir", "country": "Turkey", "category": "mediterranean_port", "lat": 38.4237, "lon": 27.1384},
    {"port_name": "Port of Mersin", "city": "Mersin", "country": "Turkey", "category": "mediterranean_port", "lat": 36.8122, "lon": 34.6415},
    {"port_name": "Port of Limassol", "city": "Limassol", "country": "Cyprus", "category": "mediterranean_port", "lat": 34.6833, "lon": 33.0333},
    {"port_name": "Port of Koper", "city": "Koper", "country": "Slovenia", "category": "mediterranean_port", "lat": 45.5469, "lon": 13.7297},
    {"port_name": "Port of Venice", "city": "Venice", "country": "Italy", "category": "mediterranean_port", "lat": 45.4408, "lon": 12.3155},
    {"port_name": "Port of Trieste", "city": "Trieste", "country": "Italy", "category": "mediterranean_port", "lat": 45.6495, "lon": 13.7768},
    {"port_name": "Port of Marseille Fos", "city": "Marseille", "country": "France", "category": "mediterranean_port", "lat": 43.2965, "lon": 5.3698},
    {"port_name": "Port of Ashdod", "city": "Ashdod", "country": "Israel", "category": "mediterranean_port", "lat": 31.7941, "lon": 34.6466},
    {"port_name": "Port of Haifa", "city": "Haifa", "country": "Israel", "category": "mediterranean_port", "lat": 32.7940, "lon": 34.9896},
    {"port_name": "Port of Beirut", "city": "Beirut", "country": "Lebanon", "category": "mediterranean_port", "lat": 33.8938, "lon": 35.5018},
    {"port_name": "Port of Latakia", "city": "Latakia", "country": "Syria", "category": "mediterranean_port", "lat": 35.5180, "lon": 35.7900},
    {"port_name": "Port Said Port", "city": "Port Said", "country": "Egypt", "category": "mediterranean_port", "lat": 31.2653, "lon": 32.2858},
    {"port_name": "Damietta Port", "city": "Damietta", "country": "Egypt", "category": "mediterranean_port", "lat": 31.4167, "lon": 31.8167},
    {"port_name": "Suez Canal Container Terminal (SCCT)", "city": "Port Said East", "country": "Egypt", "category": "mediterranean_port", "lat": 31.2185, "lon": 32.3275},
    {"port_name": "Ain Sokhna Port", "city": "Ain Sokhna", "country": "Egypt", "category": "middle_east_port", "lat": 29.6105, "lon": 32.3168}, # On Red Sea, usually grouped with Middle East
]