"""column changes and default changes

Revision ID: ede0a6a84e01
Revises: 
Create Date: 2025-08-02 16:40:14.534703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede0a6a84e01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create schema if not exists "rfq"')
    op.create_table('rfq_tbl',
    sa.Column('rfq_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pol', sa.Text(), nullable=True),
    sa.Column('pod', sa.Text(), nullable=True),
    sa.Column('contact_names', sa.Text(), nullable=True),
    sa.Column('contact_numbers', sa.Text(), nullable=True),
    sa.Column('pickup_addresses', sa.Text(), nullable=True),
    sa.Column('delivery_addresses', sa.Text(), nullable=True),
    sa.Column('package_summary', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'IN_PROGRESS'"), nullable=True),
    sa.Column('reply_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rfq_id'),
    schema='rfq'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfq_tbl', schema='rfq')
    op.execute('drop schema if exists "rfq"')
    # ### end Alembic commands ###
